package com.ninjendo.rave.util;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public interface FilterAttributes {
	public static String[] INCLUDED_ALL_CITIES = 
			new String[]{"ACWORTH","ADAIRSVILLE","ALPHARETTA","ATHENS","ATLANTA","AUSTELL","BRASELTON","CANTON","CARTERSVILLE","CEDARTOWN","CHAMBLEE","COLLEGE PARK","CONVINGTON","CONYERS","COVINGTON","CUMMING","DALLAS","DECATUR","DOUGLASVILLE","DUNWOODY","ELLENWOOD","FAIRBURN","FAYETTEVILLE","FLOWERY BRANCH","FOREST PARK","FORSYTH","GAINESVILLE","HIRAM","KENNESAW","LA FAYETTE","LAFAYETTE","LAWRENCEVILLE","LITHIA SPRINGS","MABLETON","MACON","MARIETTA","MCDONOUGH","MONROE","NEWNAN","NORCROSS","PALMETTO","PEACHTREE CITY","PEMBROKE","POWDER SPRINGS","RIVERDALE","ROME","ROSWELL","SANDY SPRINGS","SAVANNAH","SCOTTDALE","SHARPSBURG","SILVER CREEK","SMYRNA","SNELLVILLE","STONE MOUNTAIN","SUGAR HILL","SUWANEE","WOODSTOCK"
		};
	public static String[] INCLUDED_CITIES = 
			new String[]{"ACWORTH","ALPHARETTA","ATLANTA","AUSTELL","CANTON","CARTERSVILLE","CEDARTOWN","CHAMBLEE","COLLEGE PARK","CONYERS","CUMMING","DALLAS","DECATUR","DOUGLASVILLE","DUNWOODY","ELLENWOOD","FAIRBURN","FLOWERY BRANCH","FOREST PARK","HIRAM","KENNESAW","LAWRENCEVILLE","LITHIA SPRINGS","MABLETON","MARIETTA","NORCROSS","PEACHTREE CITY","POWDER SPRINGS","RIVERDALE","ROSWELL","SANDY SPRINGS","SAVANNAH","SCOTTDALE","SHARPSBURG","SMYRNA","SNELLVILLE","STONE MOUNTAIN","SUGAR HILL","SUWANEE","WOODSTOCK"
		};
	//far as f&#** -- LAFAYETTE, PEMBROKE, covington, savannah
	public Set<String> INCLUDED_CITIES_SET = new HashSet<String>(Arrays.asList(INCLUDED_CITIES));
	
	//TODO: set max character length for seller names
	public int MAX_NAME_LENGTH = 50;
	
	public static final String[] EXCLUDED_ZIP = new String[]{"30310", "30314", "30330", "30313", "30344", "30315", "30318"};
	public static final BigDecimal MAX_PRICE = new BigDecimal(350000);
	public static final String[] EXCLUDED_NAMES = new String[]{"LLC", "CORP"};
	
	public static final BigDecimal HUD_PURCHASE_PRICE_FACTOR = new BigDecimal(0.9388);
	public static final BigDecimal BROKER_FEE = new BigDecimal(295);
	public static final BigDecimal FMLS_FEE_FACTOR = new BigDecimal(0.0012);
}
