management:
  server:
    port: 9001

upload:
  uploadPath: C:/hud/
  hudNetBidFile: "HUD Net Bid - Sheet1.csv"

  
crawler:
  userAgent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
  googleSearchUrl: "https://www.google.com/#q="
  queryResultLimit: "&num=20"
  hudSearchResultInExcelUrl: "http://www.hudhomestore.com/pages/ListExportToExcel.aspx?buyerType=Investor&sState=GA"
  zillowUrlPattern: http[s]{0,1}://www\\.zillow.+_zpid
  redfinUrlPattern:


sfdata:
  hostUrl: https://data.sfgov.org
  contextPath: /resource/rqzj-sfat.json
  appToken: <TOKEN>
  updateInterval: 1 # hours

redis:
  hostname: localhost
  port: 6379
  password:

database:
#  driverClass: com.mysql.jdbc.Driver
  hostUrl: jettolano.com
#  url: jdbc:mysql://jettolano.com:3306/artotoyc_leadmanager
#  user: 
#  password: 
#  properties:
#    hibernate.dialect: org.hibernate.dialect.H2Dialect
#    hibernate.hbm2ddl.auto: create
#    hibernate.jdbc.batch_size: 50

logging:
  level: 
    root: DEBUG
  
zillow:
  webserviceid :
  webserviceIdAlternate: 
  compsCount: 10
  searchResultsUrl: http://www.zillow.com/webservice/GetSearchResults.htm
  deepSearchResultsUrl: http://www.zillow.com/webservice/GetDeepSearchResults.htm
  zestimateUrl: http://www.zillow.com/webservice/GetZestimate.htm
  compsUrl: http://www.zillow.com/webservice/GetComps.htm
  deepCompsUrl: http://www.zillow.com/webservice/GetDeepComps.htm

google:
  gsheetApiKey: 
  gsheetClientId: 
  gsheetClientSecret: 
  gmailApiKey: 
  gmailClientId: 
  gmailClientSecret: 
  responseType: code
  tokenType: Bearer
  approvalPrompt: auto

hud:
  defaultSearchUrl: "http://www.hudhomestore.com/pages/ListExportToExcel.aspx?sState=GA"
  searchUrl: "http://www.hudhomestore.com/pages/ListExportToExcel.aspx?sState="   
